name: Deploy on ghpage!

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          persist-credentials: false

      - name: Install
        run: yarn install

      - name: Build
       env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          yarn autoclean
          yarn build

      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
